project_name: wait-for-es

before:
  hooks:
    # you may remove this if you don't use vgo
    - go mod download
    # you may remove this if you don't need go generate
    # - go generate ./...

builds:
  - main: ./cli/wait-for-es
    binary: wait-for-es
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0

archives:
  - replacements:
      darwin: MacOS
      linux: Linux
      windows: Windows
      amd64: 64-bit

brew:
  github:
    owner: blacktop
    name: homebrew-tap
  folder: Formula
  homepage: "https://github.com/blacktop/wait-for-es"
  description: "Wait until Elasticsearch become available"
  test: |
    system "#{bin}/wait-for-es --version"

checksum:
  name_template: "checksums.txt"

sign:
  artifacts: checksum

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
